#161 - profile completeness progress bar
esnvutbrno/buena-fiesta pull request #196
Opened 2023-08-29 12:13 UTC by petrceska

Profile bar is loaded according to how many fields in profile is filled

2023-08-29 19:49 UTC, thejoeejoee requested changes

2023-08-29 19:49 UTC, thejoeejoee commented on fiesta/apps/accounts/templatetags/user_profile.py
> +    fields = profile._meta.get_fields()  # Get all field names of UserProfile
it's a little bit more complicated then using all UserProfile fields:

- [SectionsConfiguration](https://github.com/esnvutbrno/buena-fiesta/blob/48245f36e17bbc44d4eb78a628294eb0999f9aeb/fiesta/apps/sections/models/configuration.py#L15-L50) defines fields, which are available/optional/required for all users relating to the specific section
- that's why the UserProfileForm is [constructed dynamically](https://github.com/esnvutbrno/buena-fiesta/blob/4f70dd96df4b63e5fb156a4504fc5377581725ab/fiesta/apps/accounts/forms/profile.py#L24-L64) based on all memberships of user
- so the profile completeness cannot be computed from all `UserProfile` fields, but only from the available ones for specific user
- probably the best would be to extract the [`fields_to_include` logic](https://github.com/esnvutbrno/buena-fiesta/blob/cf35f0d3f2e27bb2f59ba62b0d89ff7b8c149440/fiesta/apps/accounts/forms/profile.py#L35-L57) to function, which returns list of fields based on given user
- and the function from previous point would be called here, so no all fields are included in formula

2023-09-05 09:29 UTC, petrceska commented on fiesta/apps/accounts/templatetags/user_profile.py
> +    fields = profile._meta.get_fields()  # Get all field names of UserProfile
fixed

2023-09-06 17:50 UTC, thejoeejoee requested changes

2023-09-06 17:50 UTC, thejoeejoee commented on fiesta/apps/accounts/templatetags/user_profile.py
> +    fields = UserProfileForm().get_form_fields(user)  # Get all field names of UserProfile
it's classmethod, no need to make an instance for calling the `get_form_fields`

```suggestion
    fields = UserProfileForm.get_form_fields(user)  # Get all field names of UserProfile
```

2023-09-06 17:50 UTC, thejoeejoee commented on fiesta/apps/accounts/forms/profile.py
> +            confs = cls.get_user_configuration(user)
`cls.get_user_configuration(user)` is called here in callback, so for each field in form, which would be definitely a performance problem -- `confs` are invariant here basically, so it could be loaded before callback definition

2023-09-06 17:50 UTC, thejoeejoee commented on fiesta/apps/accounts/templatetags/user_profile.py
> +        if field_value is None or field_value == '':
```suggestion
        if field_value is None or field_value == '':  # False is counted as filled field intentionally 
```

2023-09-07 18:13 UTC, petrceska commented
pre-commit.ci autofix

2023-09-08 09:25 UTC, petrceska commented on fiesta/apps/accounts/templatetags/user_profile.py
> +    fields = UserProfileForm().get_form_fields(user)  # Get all field names of UserProfile
done

2023-09-08 09:39 UTC, petrceska commented on fiesta/apps/accounts/templatetags/user_profile.py
> +        if field_value is None or field_value == '':
added slightly different comment

2023-09-10 17:08 UTC, thejoeejoee commented
pre-commit.ci autofix

2023-09-10 17:51 UTC, thejoeejoee approved these changes

2023-09-13 16:27 UTC, merged